### PR TITLE
cljfx.fx refactor

### PR DESCRIPTION
**Pull request by ertugrulcetin**
@vlaaad hope you like it :)

### CODE REVIEW

**Comment by vlaaad** [comment]
Hi @ertugrulcetin, many thanks for your interest in cljfx! 

Before we discuss the changes, can you please describe what is the problem you want to solve here?

**Comment by ertugrulcetin** [comment]
@vlaaad yeah, of course. Since `keyword->lifecycle-delay` hash map statically defined, I thought a dynamic way of creating it might be a good option here. When you add a new component, it's not necessary to add to the hash map anymore. Tried to avoid duplication here.

**Comment by vlaaad** [comment]
So the problem is information duplication in files and in this map? I agree it's not great, but I think it's a good trade-off: what is good about it is that it's explicit — it's easy to see what you have available for use, grouped by component kind. Making it dynamic will require more work for the user to know what's available, and `get-available-fx-types` is not enough because not every ns in cljfx.fx directory has a `lifecycle` var (e.g. nses for abstract base classes that are used by other cljfx.fx nses). 

I considered it and came to the conclusion that I don't want this solution to the duplication problem, sorry.

**Comment by ertugrulcetin** [comment]
I understand  👍

**Pull request closed without merging**
